server:
  port: 8083

spring:
  application:
    name: book-service

firebase:
  service-account-path: ${FIREBASE_SERVICE_ACCOUNT_PATH:firebase-service-account.json}
  project-id: studyforge-8d9b6

management:
  endpoints:
    web:
      exposure:
        include: health, info

logging:
  level:
    com.bookstore: DEBUG
