server:
  port: 8082

spring:
  application:
    name: user-service

firebase:
  service-account-path: ${FIREBASE_SERVICE_ACCOUNT_PATH:firebase-service-account.json}
  project-id: studyforge-8d9b6

management:
  endpoints:
    web:
      exposure:
        include: health, info
